//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "ih_houses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Option<i32>,
    pub area_id: Option<i32>,
    pub title: Option<String>,
    pub price: Option<i32>,
    pub address: Option<String>,
    pub room_count: Option<i32>,
    pub acreage: Option<i32>,
    pub unit: Option<String>,
    pub capacity: Option<i32>,
    pub beds: Option<String>,
    pub deposit: Option<i32>,
    pub min_days: Option<i32>,
    pub max_days: Option<i32>,
    pub order_count: Option<i32>,
    pub default_image_url: Option<String>,
    pub created_date: Option<DateTime>,
    pub updated_date: Option<DateTime>,
    pub is_delete: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
