//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "ih_orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Option<i32>,
    pub house_id: Option<i32>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub days: Option<i32>,
    pub price: Option<i32>,
    pub amount: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    pub status: Option<String>,
    pub trade_no: Option<String>,
    pub created_date: Option<DateTime>,
    pub updated_date: Option<DateTime>,
    pub is_delete: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
