//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

pub mod prelude;

pub mod ih_areas;
pub mod ih_facilities;
pub mod ih_house_facilities;
pub mod ih_house_images;
pub mod ih_houses;
pub mod ih_orders;
pub mod ih_users;
