//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

pub use super::ih_areas::Entity as IhAreas;
pub use super::ih_facilities::Entity as IhFacilities;
pub use super::ih_house_facilities::Entity as IhHouseFacilities;
pub use super::ih_house_images::Entity as IhHouseImages;
pub use super::ih_houses::Entity as IhHouses;
pub use super::ih_orders::Entity as IhOrders;
pub use super::ih_users::Entity as IhUsers;
